spring:
    application:
        name: audit-service
    flyway:
        enabled: false
    datasource:
        url: jdbc:postgresql://localhost:5432/audit
        username: postgres
        password: postgres
        # hikari:
        #     minimum-idle: 2
        #     maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: audit-service
logging:
    level:
        root: INFO
        com.global.audit: DEBUG